apiVersion: apps/v1
kind: Deployment
metadata:
  name: telescope-image
  namespace: telescope
  labels:
    app: telescope-image
    tier: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telescope-image
  template:
    metadata:
      labels:
        app: telescope-image
        tier: microservice
    spec:
      containers:
        - name: image
          image: telescope/image:local
          imagePullPolicy: Never
          ports:
            - containerPort: 4444
          envFrom:
            - configMapRef:
                name: telescope-config
            - secretRef:
                name: telescope-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 4444
            initialDelaySeconds: 15
            periodSeconds: 10
